// This is a simplified dataset of elements for the periodic table
// In a production app, this would come from the database

export const elementData = [
  {
    number: 1,
    name: "Hydrogen",
    symbol: "H",
    category: "nonmetal",
    atomic_mass: 1.008,
    group: 1,
    period: 1,
    block: "s",
    electron_configuration: "1s¹",
    electron_configuration_semantic: "1s¹",
    electron_affinity: 72.769,
    electronegativity_pauling: 2.2,
    ionization_energies: [1312.0],
    density: 0.0899,
    melting_point: 13.99,
    boiling_point: 20.271,
    discovered_by: "Henry Cavendish",
    named_by: "Antoine Lavoisier",
    description:
      "Hydrogen is a chemical element with symbol H and atomic number 1. With a standard atomic weight of 1.008, hydrogen is the lightest element on the periodic table. Hydrogen is the most abundant chemical substance in the Universe, constituting roughly 75% of all baryonic mass.",
  },
  {
    number: 2,
    name: "Helium",
    symbol: "He",
    category: "noble-gas",
    atomic_mass: 4.0026,
    group: 18,
    period: 1,
    block: "s",
    electron_configuration: "1s²",
    electron_configuration_semantic: "1s²",
    electron_affinity: -48,
    electronegativity_pauling: null,
    ionization_energies: [2372.3, 5250.5],
    density: 0.1785,
    melting_point: 0.95,
    boiling_point: 4.222,
    discovered_by: "Pierre Janssen",
    named_by: null,
    description:
      "Helium is a chemical element with symbol He and atomic number 2. It is a colorless, odorless, tasteless, non-toxic, inert, monatomic gas, the first in the noble gas group in the periodic table. Its boiling point is the lowest among all the elements.",
  },
  {
    number: 3,
    name: "Lithium",
    symbol: "Li",
    category: "alkali-metal",
    atomic_mass: 6.94,
    group: 1,
    period: 2,
    block: "s",
    electron_configuration: "1s² 2s¹",
    electron_configuration_semantic: "[He] 2s¹",
    electron_affinity: 59.6326,
    electronegativity_pauling: 0.98,
    ionization_energies: [520.2, 7298.1, 11815.0],
    density: 0.534,
    melting_point: 453.65,
    boiling_point: 1603,
    discovered_by: "Johan August Arfwedson",
    named_by: null,
    description:
      "Lithium is a chemical element with symbol Li and atomic number 3. It is a soft, silvery-white alkali metal. Under standard conditions, it is the lightest metal and the lightest solid element.",
  },
  {
    number: 4,
    name: "Beryllium",
    symbol: "Be",
    category: "alkaline-earth-metal",
    atomic_mass: 9.0122,
    group: 2,
    period: 2,
    block: "s",
    electron_configuration: "1s² 2s²",
    electron_configuration_semantic: "[He] 2s²",
    electron_affinity: -50,
    electronegativity_pauling: 1.57,
    ionization_energies: [899.5, 1757.1, 14848.7, 21006.6],
    density: 1.85,
    melting_point: 1560,
    boiling_point: 2742,
    discovered_by: "Louis Nicolas Vauquelin",
    named_by: null,
    description:
      "Beryllium is a chemical element with symbol Be and atomic number 4. It is a relatively rare element in the universe, usually occurring as a product of the spallation of larger atomic nuclei that have collided with cosmic rays.",
  },
  {
    number: 5,
    name: "Boron",
    symbol: "B",
    category: "metalloid",
    atomic_mass: 10.81,
    group: 13,
    period: 2,
    block: "p",
    electron_configuration: "1s² 2s² 2p¹",
    electron_configuration_semantic: "[He] 2s² 2p¹",
    electron_affinity: 26.7,
    electronegativity_pauling: 2.04,
    ionization_energies: [800.6, 2427.1, 3659.7, 25025.8, 32826.7],
    density: 2.34,
    melting_point: 2349,
    boiling_point: 4200,
    discovered_by: "Joseph Louis Gay-Lussac",
    named_by: null,
    description:
      "Boron is a chemical element with symbol B and atomic number 5. Produced entirely by cosmic ray spallation and supernovae and not by stellar nucleosynthesis, it is a low-abundance element in the Solar system and in the Earth's crust.",
  },
  // More elements would be added here in a complete implementation
]
